-- MySQL Script generated by MySQL Workbench
-- Sun Nov 18 16:47:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TM_VEHICULO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_VEHICULO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_VEHICULO` (
  `VCH_PLACA` VARCHAR(10) NOT NULL,
  `VCH_MARCA` VARCHAR(45) NULL,
  `VCH_MODELO` VARCHAR(45) NULL,
  `VCH_CERTIFICADO` VARCHAR(20) NULL,
  `VCH_NRO_REGISTRO` VARCHAR(20) NULL,
  `INT_ANIO` SMALLINT(4) NULL,
  `INT_NRO_EJES` SMALLINT(4) NULL,
  `DEC_TARA` DECIMAL(7,2) NULL,
  `DEC_CARGA_UTIL` DECIMAL(7,2) NULL,
  `DEC_PESO_BRUTO` DECIMAL(7,2) NULL,
  `INT_ACTIVO` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`VCH_PLACA`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `VCH_PLACA_UNIQUE` ON `mydb`.`TM_VEHICULO` (`VCH_PLACA` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`TM_TIPO_VEHICULO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_TIPO_VEHICULO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_TIPO_VEHICULO` (
  `ID_TIPO_VEHICULO` INT NOT NULL AUTO_INCREMENT,
  `VCH_DESCRIPCION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_TIPO_VEHICULO`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_TIPO_VEHICULO_UNIQUE` ON `mydb`.`TM_TIPO_VEHICULO` (`ID_TIPO_VEHICULO` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`TM_TIPO_COMBUSTIBLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_TIPO_COMBUSTIBLE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_TIPO_COMBUSTIBLE` (
  `ID_TIPO_COMBUSTIBLE` INT NOT NULL AUTO_INCREMENT,
  `VCH_DESCRIPCION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_TIPO_COMBUSTIBLE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TM_ESTADO_VEHICULO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_ESTADO_VEHICULO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_ESTADO_VEHICULO` (
  `ID_ESTADO_VEHICULO` INT NOT NULL AUTO_INCREMENT,
  `VCH_DESCRIPCION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_ESTADO_VEHICULO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TM_CARRETA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_CARRETA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_CARRETA` (
  `VCH_PLACA` VARCHAR(10) NOT NULL,
  `VCH_NRO_REGISTRO` VARCHAR(20) NULL,
  `VCH_NRO_INSCRIPCION` VARCHAR(20) NULL,
  `INT_NRO_EJES` TINYINT(1) NULL,
  `DEC_TARA` DECIMAL(7,2) NULL,
  `DEC_CARGA_UTIL` DECIMAL(7,2) NULL,
  `DEC_PESO_BRUTO` DECIMAL(7,2) NULL,
  `INT_ACTIVO` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`VCH_PLACA`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `VCH_PLACA_UNIQUE` ON `mydb`.`TM_CARRETA` (`VCH_PLACA` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`TM_COLABORADOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_COLABORADOR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_COLABORADOR` (
  `VCH_DOCUMENTO_IDENTIDAD` VARCHAR(15) NOT NULL,
  `VCH_NOMBRES` VARCHAR(45) NULL,
  `VCH_APELLIDO_PATERNO` VARCHAR(45) NULL,
  `VCH_APELLIDO_MATERNO` VARCHAR(45) NULL,
  `DTM_FECHA_NACIMIENTO` DATETIME NULL,
  `VCH_DIRECCION` VARCHAR(45) NULL,
  `VCH_TELF_CONTACTO` VARCHAR(45) NULL,
  `VCH_NRO_LICENCIA_CONDUCIR` VARCHAR(45) NULL,
  `INT_ACTIVO` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`VCH_DOCUMENTO_IDENTIDAD`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `VCH_DOCUMENTO_IDENTIDAD_UNIQUE` ON `mydb`.`TM_COLABORADOR` (`VCH_DOCUMENTO_IDENTIDAD` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`TM_TIPO_COLABORADOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_TIPO_COLABORADOR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_TIPO_COLABORADOR` (
  `ID_TIPO_COLABORADOR` INT NOT NULL AUTO_INCREMENT,
  `VCH_DESCRIPCION` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_TIPO_COLABORADOR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TM_ESTADO_CIVIL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_ESTADO_CIVIL` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_ESTADO_CIVIL` (
  `ID_ESTADO_CIVIL` INT NOT NULL AUTO_INCREMENT,
  `VCH_DESCRIPCION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_ESTADO_CIVIL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TM_GRADO_INSTRUCCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_GRADO_INSTRUCCION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_GRADO_INSTRUCCION` (
  `ID_GRADO_INSTRUCCION` INT NOT NULL AUTO_INCREMENT,
  `VCH_DESCRIPCION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_GRADO_INSTRUCCION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TM_UBICACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_UBICACION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_UBICACION` (
  `ID_UBICACION` INT NOT NULL AUTO_INCREMENT,
  `VCH_DEPARTAMENTO` VARCHAR(45) NOT NULL,
  `VCH_PROVINCIA` VARCHAR(45) NOT NULL,
  `VCH_DISTRITO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_UBICACION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TM_SUCURSAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_SUCURSAL` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_SUCURSAL` (
  `ID_SUCURSAL` INT NOT NULL AUTO_INCREMENT,
  `VCH_RUC` VARCHAR(11) NOT NULL,
  `VCH_RAZON_SOCIAL` VARCHAR(45) NOT NULL,
  `VCH_DIRECCION` VARCHAR(45) NOT NULL,
  `VCH_ZONA` VARCHAR(45) NULL,
  `VCH_TELEFONO` VARCHAR(15) NULL,
  `VCH_CELULAR` VARCHAR(10) NULL,
  `VCH_EMAIL` VARCHAR(45) NULL,
  `INT_ACTIVO` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID_SUCURSAL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TM_VIAJE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_VIAJE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_VIAJE` (
  `ID_VIAJE` INT NOT NULL AUTO_INCREMENT,
  `DTM_FECHA_SALIDA` DATETIME NULL,
  `DTM_FECHA_LLEGADA` DATETIME NULL,
  `INT_ACTIVO` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID_VIAJE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TM_ESTADO_VIAJE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_ESTADO_VIAJE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_ESTADO_VIAJE` (
  `ID_ESTADO_VIAJE` INT NOT NULL AUTO_INCREMENT,
  `VCH_DESCRIPCION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_ESTADO_VIAJE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TM_MOVIMIENTO_VIAJES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_MOVIMIENTO_VIAJES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_MOVIMIENTO_VIAJES` (
  `ID_MOVIMIENTO_VIAJES` INT NOT NULL AUTO_INCREMENT,
  `DEC_MONTO` DECIMAL(7,2) NOT NULL,
  `DTM_FECHA` DATETIME NOT NULL,
  `DESCRIPCION` VARCHAR(45) NULL,
  `VCH_RAZON_SOCIAL` VARCHAR(45) NULL,
  `VCH_NRO_COMPROBANTE` VARCHAR(45) NULL,
  `INT_ACTIVO` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID_MOVIMIENTO_VIAJES`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TM_TIPO_MOVIMIENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_TIPO_MOVIMIENTO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_TIPO_MOVIMIENTO` (
  `ID_TIPO_MOVIMIENTO` INT NOT NULL AUTO_INCREMENT,
  `VCH_DESCRIPCION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_TIPO_MOVIMIENTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TM_SERIE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_SERIE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_SERIE` (
  `ID_SERIE` INT NOT NULL AUTO_INCREMENT,
  `VCH_SERIE` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`ID_SERIE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TM_TIPO_COMPROBANTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_TIPO_COMPROBANTE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_TIPO_COMPROBANTE` (
  `ID_TIPO_COMPROBANTE` INT NOT NULL AUTO_INCREMENT,
  `VCH_TIPO_COMPROBANTEcol` VARCHAR(45) NOT NULL,
  `INT_CODIGO_COMPROBATE` INT NULL,
  PRIMARY KEY (`ID_TIPO_COMPROBANTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TM_COMPROBANTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_COMPROBANTE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_COMPROBANTE` (
  `ID_COMPROBANTE` INT NOT NULL AUTO_INCREMENT,
  `INT_NUMERO` INT NOT NULL,
  `DTM_FECHA_EMISION` DATETIME NOT NULL,
  `DEC_TOTAL` DECIMAL(7,5) NOT NULL,
  `VCH_DIRECCION_ORIGEN` VARCHAR(45) NULL,
  `VCH_DIRECCION_DESTINO` VARCHAR(45) NULL,
  `VCH_DOCUMENTO_CLIENTE` VARCHAR(45) NULL,
  `VCH_RAZON_SOCIAL_CLIENTE` VARCHAR(45) NULL,
  `DTM_FECHA_ENTREGA` DATETIME NULL,
  `VCH_OBSERVACIONES` VARCHAR(100) NULL,
  `INT_ACTIVO` TINYINT(1) NOT NULL DEFAULT 1,
  `VCH_NRO_CHEQUE` VARCHAR(20) NULL,
  `DTM_FECHA_ALMACEN` DATETIME NULL,
  PRIMARY KEY (`ID_COMPROBANTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TM_ESTADO_PAGO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_ESTADO_PAGO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_ESTADO_PAGO` (
  `ID_ESTADO_PAGO` INT NOT NULL AUTO_INCREMENT,
  `VCH_DESCRIPCION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_ESTADO_PAGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TM_ESTADO_ENTREGA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_ESTADO_ENTREGA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_ESTADO_ENTREGA` (
  `ID_ESTADO_ENTREGA` INT NOT NULL AUTO_INCREMENT,
  `VCH_DESCRIPCION` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_ESTADO_ENTREGA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TM_IGV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_IGV` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_IGV` (
  `ID_IGV` INT NOT NULL AUTO_INCREMENT,
  `VCH_DESCRIPCION` VARCHAR(45) NULL,
  `DEC_MONTO` VARCHAR(45) NULL,
  `INT_DEFAULT` VARCHAR(45) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID_IGV`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TM_ARTICULO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TM_ARTICULO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TM_ARTICULO` (
  `ID_ARTICULO` INT NOT NULL,
  `VCH_DESCRIPCION` VARCHAR(45) NULL,
  `DEC_PESO` DECIMAL(7,5) NULL,
  `DEC_FLETE` DECIMAL(7,5) NULL,
  PRIMARY KEY (`ID_ARTICULO`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
